experiment_name: "part1"
seed: 0

save_interval: 1000 # Steps to save checkpoint
log_interval: 10 # Steps to log

# data
batch_size: 8

base_path: /data
data_dir: ""
ood_dir: ""

output_dir: "${base_path}/output/${experiment_name}"
device: "cuda"
seed: 0
resume: false
ckpt_path: "${base_path}/output/${experiment_name}/checkpoints/step=29999/ckpt.pth" # Resume from checkpoint if resume is true
num_workers: 4
pin_mem: false # Pin CPU memory in DataLoader
persistent_workers: true

# train
epochs: 5

# optimizer parameters
optim: "adamw"
lr: 0.1
betas: [0.9, 0.999]
