experiment_name: "convnet-200epochs"

# data
batch_size: 128

data_dir: /raid4/datasets
ood_dir: /raid4/datasets/cifar-100-ood

output_dir: "./outputs/${experiment_name}"
device: "cuda"
seed: 0
ckpt_path: "./outputs/part1/best_model.pth" # Resume from checkpoint if resume is true
num_workers: 4
pin_mem: true # Pin CPU memory in DataLoader
persistent_workers: true
