experiment_name: "resnet50-finetune-drop-rate-0.2-wd-5e-4-50_epochs-adamw-lr_1e-3-cosine_annealing-fp16-clip_grad_3-clahe-hflip_0.5-brightness_0.5-gauss_noise_0.5-jpeg_compression_0.2_resized_crop_0.32_1.0-rotation_1.0-pad_4"

# data
batch_size: 128

transforms:
  resize_size: ${input_size}

data_dir: /raid4/datasets
ood_dir: /raid4/datasets/cifar-100-ood

output_dir: "./outputs/${experiment_name}"
device: "cuda"
seed: 0
ckpt_path: "./outputs/${experiment_name}/best_model.pth" # Resume from checkpoint if resume is true
num_workers: 4
pin_mem: true # Pin CPU memory in DataLoader
persistent_workers: true

use_fp16: true
dtype: "bf16"
device_type: "cuda"
