experiment_name: "resnet50fc2-finetune-dr-0.2-wd-0.02-50_epochs-adoptw-lr_5e-4-cosine_annealing-fp16-clip_grad_3-clahe-hflip_0.5-brightness_0.5-gauss_noise_0.5-jpeg_compression_0.2_resized_crop_0.32_1.0-rotation_1.0-pad_4-bs_256-lbl_smoothing_0.1-cutmix_or_mixup_0.5"

# data
batch_size: 256

data_dir: /raid4/datasets

output_dir: "./outputs/${experiment_name}"
device: "cuda"
seed: 0
resume: false
ckpt_path: "" # Resume from checkpoint if resume is true
num_workers: 4
pin_mem: true # Pin CPU memory in DataLoader
persistent_workers: true

transforms:
  hflip_prob: 0.5
  brightness_prob: 0.5
  gaussian_noise_prob: 0.5
  jpeg_compression_prob: 0.2
  rotation_prob: 1.0

cutmix_or_mixup: true

# train
epochs: 50
use_fp16: true
dtype: "bf16"
device_type: "cuda:0"
clip_grad: 3.0

# optimizer parameters
optim: "adoptw"
base_lr: 5e-4
min_lr: 1e-6
betas: [0.9, 0.9999]
momentum: 0.9
weight_decay: 0.02
label_smoothing: 0.1
