experiment_name: "convnet-50_epochs-adamw-cosine_annealing-fp16-clahe-hflip_0.5-brightness_0.5-color_jitter_0.8"

# data
batch_size: 128

data_dir: /raid4/datasets

output_dir: "./outputs/${experiment_name}"
device: "cuda"
seed: 0
resume: false
ckpt_path: "" # Resume from checkpoint if resume is true
num_workers: 4
pin_mem: true # Pin CPU memory in DataLoader
persistent_workers: true

# train
epochs: 50
use_fp16: true
dtype: "bf16"
device_type: "cuda"
clip_grad: 3.0

# optimizer parameters
optim: "adamw"
lr: 1e-3
min_lr: 1e-6
betas: [0.9, 0.999]
label_smoothing: 0.0
