experiment_name: "convnet-100_epochs-adamw-cosine_annealing"

# data
batch_size: 128

data_dir: /raid4/datasets

output_dir: "./outputs/${experiment_name}"
device: "cuda"
seed: 0
resume: false
ckpt_path: "" # Resume from checkpoint if resume is true
num_workers: 4
pin_mem: true # Pin CPU memory in DataLoader
persistent_workers: true

# train
epochs: 100

# optimizer parameters
optim: "adamw"
lr: 1e-3
min_lr: 1e-6
betas: [0.9, 0.999]
label_smoothing: 0.0
